### ISSUE TITLE
Some import statements are not working with Python3

### ISSUE THREAD

**Issue by kodweis** [agrewal707/pyorbit#1]
```
python3 ./pyorbit/examples/get_config.py 192.168.1.1 admin admin
Traceback (most recent call last):
  File "./pyorbit/examples/get_config.py", line 4, in <module>
    from pyorbit import Device
  File "/home/jkodweis/projects/python-orbit/pyorbit/pyorbit/__init__.py", line 1, in <module>
    from device import Device
ImportError: No module named 'device'
```

This can be fixed by prefixing the module name with a period: `from .device import Device`

**Comment by kodweis** [comment]
Fixed with commit 5695284
